name: Test
on:
  push:
    branches-ignore:
      - 'develop'
      - 'gh-pages'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir data || true
      - run: npm install
      - name: Build Nagano, Hokkaido, and Nara data
        run: node bin/build.js 20,1,29,13
      - name: Test
        run: npx mocha
